name: jpl
favicon: null
layout_spectrum: 0.8959136127959937
typography_spectrum: 0.4226622919086367
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: JPL
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#F84800'
    - '#6E2000'
  brandStrength: 0.7437276
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
