name: jpl
favicon: null
layout_spectrum: 0.8959136127959937
typography_spectrum: 0.4226622919086367
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6836467580869794
  lightness: 0.13693770859390497
  saturation: 0.07876942050643265
  rhythmicContrast: 0.1863013869151473
purpose: []
